### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by Evajuliab** [THP-Paris/Puppease-thp#4]
** why **

permettre la visualisation des chiens du site

** to-do **

- [ ] faire seed chiens
- [ ] utiliser les différents éléments CSS du template pour mettre en forme un index des chiens
- [ ] Utiliser Ajax pour mettre toujours le dernier chien inscrit en haut

** must have **

Une homepage sur l'index des chiens inscrits sur l'app
