### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by Evajuliab** [THP-Paris/Puppease-thp#8]
** why **

la demande des coordonnées d'un propriétaire sera payante 

** to-do **

- [ ] intégrer Stripe au site 

- [ ] créer les clés API

- [ ] intégrer le bouton paiement sur la show du dog + sur la liste d'interêt

** must have**

Stripe intégré pour permettre le paiement avant de déclencher l'envoi de l'email avec les coordonnées
